name: ITO OS Web Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - uses: actions/checkout@v3

      # Set up Node.js and install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      # Build the app (assuming there's a build step defined in package.json)
      - name: Build the app
        run: npm run build # Ensure this matches the build script in your package.json

  deliverit:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the code again in this job
      - name: Check out code
        uses: actions/checkout@v3

      # Build and push Docker image to Docker Hub
      - name: Build Docker image and push to Hub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: panseeBadry/iti_dockerLab # Replace with your Docker Hub username and repo name
          registry: docker.io
          dockerfile: Dockerfile # Assuming Dockerfile is at the root of your repo
          username: "${{ secrets.HUB_USERNAME }}"
          password: "${{ secrets.HUB_PASSWORD }}"
          tags: latest

